/*
 * generated by Xtext 2.26.0.M2
 */
package br.edu.ufrn.myhtml.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractHtmlModelScopeProvider extends DelegatingScopeProvider {
}
