/*
 * generated by Xtext 2.26.0.M2
 */
package br.edu.ufrn.myhtml.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractHtmlModelValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(br.edu.ufrn.myhtml.htmlModel.HtmlModelPackage.eINSTANCE);
		return result;
	}
}
