/*
 * generated by Xtext 2.26.0.M2
 */
package br.edu.ufrn.myhtml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class HtmlModelUiModule extends AbstractHtmlModelUiModule {

	public HtmlModelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
