/*
 * generated by Xtext 2.26.0.M2
 */
package br.edu.ufrn.myhtml;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class HtmlModelStandaloneSetup extends HtmlModelStandaloneSetupGenerated {

	public static void doSetup() {
		new HtmlModelStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
