/*
 * generated by Xtext 2.26.0.M2
 */
package br.edu.ufrn.myhtml.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class HtmlModelAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("br/edu/ufrn/myhtml/parser/antlr/internal/InternalHtmlModel.tokens");
	}
}
