/*
 * generated by Xtext 2.26.0.M2
 */
package br.edu.ufrn.myhtml.parser.antlr;

import br.edu.ufrn.myhtml.parser.antlr.internal.InternalHtmlModelParser;
import br.edu.ufrn.myhtml.services.HtmlModelGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class HtmlModelParser extends AbstractAntlrParser {

	@Inject
	private HtmlModelGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalHtmlModelParser createParser(XtextTokenStream stream) {
		return new InternalHtmlModelParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "MyHtmlModel";
	}

	public HtmlModelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(HtmlModelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
