/**
 * generated by Xtext 2.26.0.M2
 */
package br.edu.ufrn.myhtml.htmlModel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Paragraph</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.edu.ufrn.myhtml.htmlModel.Paragraph#getColor <em>Color</em>}</li>
 *   <li>{@link br.edu.ufrn.myhtml.htmlModel.Paragraph#getContent <em>Content</em>}</li>
 * </ul>
 *
 * @see br.edu.ufrn.myhtml.htmlModel.HtmlModelPackage#getParagraph()
 * @model
 * @generated
 */
public interface Paragraph extends EObject
{
  /**
   * Returns the value of the '<em><b>Color</b></em>' attribute.
   * The literals are from the enumeration {@link br.edu.ufrn.myhtml.htmlModel.BasicColors}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Color</em>' attribute.
   * @see br.edu.ufrn.myhtml.htmlModel.BasicColors
   * @see #setColor(BasicColors)
   * @see br.edu.ufrn.myhtml.htmlModel.HtmlModelPackage#getParagraph_Color()
   * @model
   * @generated
   */
  BasicColors getColor();

  /**
   * Sets the value of the '{@link br.edu.ufrn.myhtml.htmlModel.Paragraph#getColor <em>Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Color</em>' attribute.
   * @see br.edu.ufrn.myhtml.htmlModel.BasicColors
   * @see #getColor()
   * @generated
   */
  void setColor(BasicColors value);

  /**
   * Returns the value of the '<em><b>Content</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Content</em>' attribute.
   * @see #setContent(String)
   * @see br.edu.ufrn.myhtml.htmlModel.HtmlModelPackage#getParagraph_Content()
   * @model
   * @generated
   */
  String getContent();

  /**
   * Sets the value of the '{@link br.edu.ufrn.myhtml.htmlModel.Paragraph#getContent <em>Content</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Content</em>' attribute.
   * @see #getContent()
   * @generated
   */
  void setContent(String value);

} // Paragraph
