/**
 * generated by Xtext 2.26.0.M2
 */
package br.edu.ufrn.myhtml.htmlModel;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Section</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link br.edu.ufrn.myhtml.htmlModel.Section#getTitle <em>Title</em>}</li>
 *   <li>{@link br.edu.ufrn.myhtml.htmlModel.Section#getSize <em>Size</em>}</li>
 *   <li>{@link br.edu.ufrn.myhtml.htmlModel.Section#getParagraphs <em>Paragraphs</em>}</li>
 * </ul>
 *
 * @see br.edu.ufrn.myhtml.htmlModel.HtmlModelPackage#getSection()
 * @model
 * @generated
 */
public interface Section extends EObject
{
  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see br.edu.ufrn.myhtml.htmlModel.HtmlModelPackage#getSection_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link br.edu.ufrn.myhtml.htmlModel.Section#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

  /**
   * Returns the value of the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size</em>' attribute.
   * @see #setSize(int)
   * @see br.edu.ufrn.myhtml.htmlModel.HtmlModelPackage#getSection_Size()
   * @model
   * @generated
   */
  int getSize();

  /**
   * Sets the value of the '{@link br.edu.ufrn.myhtml.htmlModel.Section#getSize <em>Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size</em>' attribute.
   * @see #getSize()
   * @generated
   */
  void setSize(int value);

  /**
   * Returns the value of the '<em><b>Paragraphs</b></em>' containment reference list.
   * The list contents are of type {@link br.edu.ufrn.myhtml.htmlModel.Paragraph}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Paragraphs</em>' containment reference list.
   * @see br.edu.ufrn.myhtml.htmlModel.HtmlModelPackage#getSection_Paragraphs()
   * @model containment="true"
   * @generated
   */
  EList<Paragraph> getParagraphs();

} // Section
