/*
 * generated by Xtext 2.26.0.M2
 */
package br.edu.ufrn.myhtml.ide;

import br.edu.ufrn.myhtml.HtmlModelRuntimeModule;
import br.edu.ufrn.myhtml.HtmlModelStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class HtmlModelIdeSetup extends HtmlModelStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new HtmlModelRuntimeModule(), new HtmlModelIdeModule()));
	}
	
}
